services:
  simker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_DIR:-./}:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - TZ=Europe/Paris
      - TERM=xterm-256color
    working_dir: /workspace
    user: ubuntu
