services:
  simker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - TZ=Europe/Paris
    working_dir: /workspace
    user: designer
